const OrderActionTypes = {
    ORDER_CREATE_REQUEST:'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS:'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAILURE:'ORDER_CREATE_FAILURE',

    ORDER_DETAILS_REQUEST:'ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS:'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAILURE:'ORDER_DETAILS_FAILURE',
};

export default OrderActionTypes;